name: SauceDemo Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  all-tests:
    name: Run All Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # cache Playwright browsers
      - name: Cache Playwright Browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      # Install ALL browsers + dependencies
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: mvn exec:java -e \
          -D exec.mainClass=com.microsoft.playwright.CLI \
          -D exec.args="install --with-deps"

      - name: Resolve dependencies
        run: mvn dependency:resolve

      - name: Run All Tests
        run: mvn clean test

      - name: Install Allure CLI
        if: always()
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      # Generate report even if tests fail
      - name: Generate Single-File Allure Report
        if: always()
        run: allure generate target/allure-results --clean --single-file -o target/allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report/index.html
          retention-days: 7

      - name: Upload Debug Artifacts (Failure Only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            src/screenshots
            target/traces
            target/surefire-reports
          retention-days: 7